namespace TidyHPC.Routers.Urls;
internal class Mime
{
    public static string DetectByFileExtension(string fileExtension)
    {
        return fileExtension switch
        {
            ".htm" or ".html" => "text/html",
            ".css" => "text/css",
            ".js" => "application/javascript",
            ".json" => "application/json",
            ".xml" => "application/xml",
            ".zip" => "application/zip",
            ".pdf" => "application/pdf",
            ".doc" => "application/msword",
            ".xls" => "application/vnd.ms-excel",
            ".ppt" => "application/vnd.ms-powerpoint",
            ".gif" => "image/gif",
            ".png" => "image/png",
            ".jpeg" or ".jpg" => "image/jpeg",
            ".bmp" => "image/bmp",
            ".ico" => "image/x-icon",
            ".svg" => "image/svg+xml",
            ".mp3" => "audio/mpeg",
            ".wav" => "audio/wav",
            ".mp4" => "video/mp4",
            ".webm" => "video/webm",
            ".ogg" => "video/ogg",
            ".flv" => "video/x-flv",
            ".avi" => "video/x-msvideo",
            ".wmv" => "video/x-ms-wmv",
            ".mpg" or ".mpeg" => "video/mpeg",
            ".txt" => "text/plain",
            ".csv" => "text/csv",
            ".rtf" => "application/rtf",
            ".docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ".xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ".pptx" => "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            ".rar" => "application/vnd.rar",
            ".7z" => "application/x-7z-compressed",
            ".tar" => "application/x-tar",
            ".gz" => "application/gzip",
            ".bz2" => "application/x-bzip2",
            ".xz" => "application/x-xz",
            ".exe" => "application/x-msdownload",
            ".msi" => "application/x-msi",
            ".apk" => "application/vnd.android.package-archive",
            ".deb" => "application/vnd.debian.binary-package",
            ".rpm" => "application/x-rpm",
            ".dmg" => "application/x-apple-diskimage",
            ".iso" => "application/x-iso9660-image",
            ".img" => "application/x-raw-disk-image",
            ".bin" => "application/octet-stream",
            ".dll" => "application/octet-stream",
            ".so" => "application/octet-stream",
            ".class" => "application/octet-stream",
            ".jar" => "application/java-archive",
            ".war" => "application/java-archive",
            ".ear" => "application/java-archive",
            ".swf" => "application/x-shockwave-flash",
            ".fla" => "application/octet-stream",
            ".psd" => "application/octet-stream",
            ".ai" => "application/octet-stream",
            _ => "application/octet-stream"
        };
    }
}
